2020.08.14-01

diff --git a/gsa-gen b/gsa-gen
--- a/gsa-gen
+++ b/gsa-gen
@@ -1,214 +1,333 @@
-#!/bin/bash
-# 인코딩 : ubuntu utf-8 lf
-# GitHub : https://github.com/ssokka/Ubuntu/blob/master/gsa-gen
+#!/usr/bin/env bash
 
-# 스크립트
-# 설명      : 구글 서비스 계정 생성
-# 실행 환경 : 리눅스 Bash
-# 개발 환경 : windows 10 x64 wsl2 ubuntu 20.04 tls
-# 한줄 실행 : curl https://raw.githubusercontent.com/ssokka/ubuntu/master/gsa-gen | bash -
-# 일반 실행 : bash gsa-gen
-# 다운로드  : curl -O https://raw.githubusercontent.com/ssokka/ubuntu/master/gsa-gen
+# 인코딩
+# utf-8 lf
+
+# GitHub
+# https://github.com/ssokka/Ubuntu/blob/master/gsa-gen
+
+# 구글 서비스 계정 생성 스크립트
+
+# 실행 환경
+# 우분투 또는 윈도우 WSL 우분투
+
+# 개발 환경
+# windows 10 x64 wsl2 ubuntu 20.04 tls
+
+# SJVA 도커 환경은 Bash 쉘을 먼저 설치해야 합니다.
+# SJVA 웹 >> 시스템 >> Command
+# apk add --no-cache bash
+
+# 한줄 실행 방법
+# 스크립트 기본 변수 값 사용 시
+# curl https://raw.githubusercontent.com/ssokka/ubuntu/master/gsa-gen | bash
+
+# 다운로드 후 실행 방법
+# 스크립트 변수 값 수정 사용 시
+# curl -O https://raw.githubusercontent.com/ssokka/ubuntu/master/gsa-gen
+# bash gsa-gen
 
 # 특징
 # 불필요한 Google APIs 제거
-# 서비스 계정 및 키 파일을 일정한 규칙으로 생성
-# 구글 그룹스에 서비스 계정 추가 시 복사/붙여넣기용 텍스트 파일 생성
-
-# 기종 프로젝트 이름을 사용할 경우 아래
-# PROJECT_EXIST=""를 PROJECT_EXIST="기존프로젝트이름"으로
-# 수정하여 사용하시기 바랍니다.
+# 일정한 규칙의 프로젝트명, 서비스 계정명, 키 파일명 생성
+# 서비스 계정 키 중복 방지
+# 구글 그룹에 서비스 계정 추가 시 복사/붙여넣기용 텍스트 파일 생성
 
 # 변수
-# PROJECT_EXIST 변수를 지정할 경우
-# 3가지 변수(PROJECT_START, PROJECT_END, PROJECT_INFIX)는 무시된다.
-PROJECT_EXIST=""        # 기존 프로젝트 이름
-PROJECT_START=1         # 프로젝트 시작 번호
-PROJECT_END=2           # 프로젝트 종료 번호
-PROJECT_INFIX=rclone    # 프로젝트 이름 접요사
-NUM_SAS_PER_PROJECT=100 # 프로젝트 당 서비스 계정 생성 갯수, 최대 100개
-DIR_WORK=$(pwd)         # 기본 저장 경로
-DIR_KEY=accounts        # 서비스 계정 키 저장 폴더
+# 기존 프로젝트명(OLD_PROJECT_NAME)을 지정할 경우
+# 3개의 변수(PROJECT_START, PROJECT_END, PROJECT_PREFIX)는 무시된다.
 
-# 참고
-# 프로젝트 명 규칙  : 구글_ID-PROJECT_INFIX-프로젝트_번호 [ex] test-rclone-01
-# 구글 서비스 계정  : https://cloud.google.com/iam/docs/service-accounts?hl=ko
-# 구글 클라우드 SDK : https://cloud.google.com/sdk/docs?hl=ko
-# gcloud            : https://cloud.google.com/sdk/gcloud/reference?hl=ko
-# sa-gen            : https://github.com/88lex/sa-gen
+# 변수 - 기존 프로젝트명, 기존 프로젝트 수정 시 사용
+OLD_PROJECT_NAME=""
+
+# 변수 - 프로젝트 시작 번호
+PROJECT_START=1
+
+# 변수 - 프로젝트 종료 번호
+PROJECT_END=1
+
+# 변수 - 프로젝트명 접두사
+PROJECT_PREFIX=rclone
+
+# 변수 - 프로젝트 당 서비스 계정 생성 개수, 최대 100개
+NUM_SAS_PER_PROJECT=100
+
+# 변수 - 기본 작업 폴더
+DIR_WORK=${HOME}
+
+# 변수 - SJVA Rclone Expand 작업 폴더
+DIR_SJVA_WORK="/app/data/rclone_expand"
+
+# 변수 - 서비스 계정 키 폴더
+DIR_KEY=accounts
+
+# 규칙 - 예시
+# xxx-p01-sa001@xxx-rclone01
+# xxx - 구글 계정
+# p01 - 프로젝트 번호
+# sa001 - 서비스 계정 번호
+# rclone01 - 프로젝트명
+
+# 참고 - 구글 서비스 계정
+# https://cloud.google.com/iam/docs/service-accounts?hl=ko
+
+# 참고 - 구글 클라우드 SDK
+# https://cloud.google.com/sdk/docs?hl=ko
+# 참고 - gcloud
+# https://cloud.google.com/sdk/gcloud/reference?hl=ko
+
+# 참고 - sa-gen
+# https://github.com/88lex/sa-gen
+
+# 참고 - AutoRclone
+# https://github.com/xyou365/AutoRclone
+
+# 참고 - gclone            : https://github.com/donwa/gclone
 
 
-
-if [ -n "${PROJECT_EXIST}" ]; then
-	PROJECT_START=1
-	PROJECT_END=1
-fi
+init() {
+	if [[ -n "${OLD_PROJECT_NAME}" ]]; then
+		PROJECT_START=1
+		PROJECT_END=1
+	fi
+	if [[ PROJECT_END -gt 12 ]]; then
+		PROJECT_END=12
+	fi
+	if [[ -f "/app/sjva.py" ]]; then
+		DIR_WORK=${DIR_SJVA_WORK}
+	fi
+}
 
 timestamp(){
-	echo "[$(date '+%Y-%m-%d %H:%M:%S')]"
+	echo -e "[$(date '+%Y-%m-%d %H:%M:%S')]"
 }
 
-install_sdk() {
-	local bin=/usr/bin/gcloud
-	if [ ! -f ${bin} ]; then
+install() {
+	which bash &>/dev/null
+	if [[ $? != 0 ]]; then
+		echo -e "$(timestamp) Bash 설치"
 		echo
-		echo -e "$(timestamp) [INFO] 구글 클라우드 SDK 설치"
-		local list=/etc/apt/sources.list.d/google-cloud-sdk.list
-		sudo rm -f "${list}"
-		echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a "${list}"
-		curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
-		sudo apt update -y && sudo apt install google-cloud-sdk -y
+		apk add --no-cache bash
+		which bash &>/dev/null
+		if [[ $? != 0 ]]; then
+			echo
+			echo -e "$(timestamp) [ERROR] Bash 설치 실패"
+			echo
+			exit
+		fi
+		echo
 	fi
-	if [ ! -f ${bin} ]; then
-		echo -e "$(timestamp) [ERROR] 구글 클라우드 SDK 설치 확인 필요"
-		echo -e "$(timestamp) + dpkg --list | grep google-cloud-sdk"
+	export PATH=$PATH:$HOME/google-cloud-sdk/bin
+	which gcloud &>/dev/null
+	if [[ $? != 0 ]]; then
+		echo -e "$(timestamp) 구글 클라우드 SDK 설치"
 		echo
-		exit
+		curl https://sdk.cloud.google.com > install.sh && bash install.sh --disable-prompts
+		which gcloud &>/dev/null
+		if [[ $? == 0 ]]; then
+			echo -e "$(timestamp) 구글 클라우드 SDK 삭제 명령어"
+			echo -e "$(timestamp) rm -rf ${HOME}/google-cloud-sdk"
+		else
+			echo -e "$(timestamp) [ERROR] 구글 클라우드 SDK 설치 실패"
+			echo
+			exit
+		fi
+		echo
 	fi
 }
 
-auth_login() {
-	echo
-	echo -e "$(timestamp) [INFO] 구글 클라우드 SDK 자격 증명"
+auth() {
 	gcloud auth revoke --all &>/dev/null
+	echo -e "$(timestamp) 구글 클라우드 SDK 자격 증명"
+	echo
+	echo -e "   + 1. 웹 브라우저에서 아래 링크로 이동하세요."
+	echo -e "   + 2. 서비스 계정을 생성/수정할 구글 계정으로 로그인하세요."
+	echo -e "   + 3. Google Cloud SDK 엑세스 요청 화면에서 허용을 클릭하세요."
+	echo -e "   + 4. 인증 코드를 복사하세요."
+	echo -e "   + 5. 인증 코드 입력(Enter verification code)에 붙여넣으세요."
+	echo
 	gcloud auth login --brief
-	if [ $? != 0 ]; then
+	echo
+	if [[ $? != 0 ]]; then
 		echo -e "$(timestamp) [ERROR] 구글 클라우드 SDK 자격 증명 실패"
 		echo
 		exit
 	fi
-	echo
 	local pattern="\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b"
-	ACCOUNT=$(echo $(gcloud auth list 2>&1) | grep -Eo ${pattern})
+	ACCOUNT=$(gcloud auth list 2>&1 | grep -Eo ${pattern})
 	if [[ "${ACCOUNT}" == "" ]]; then
-		ACCOUNT=$(echo $(gcloud config list 2>&1) | grep -Eo ${pattern})
+		ACCOUNT=$(gcloud config list 2>&1 | grep -Eo ${pattern})
 	fi
 	if [[ "${ACCOUNT}" != "" ]]; then
 		ID=$(echo ${ACCOUNT} | grep -Eo "\b^[A-Za-z0-9._%+-]+\b" | sed "s/\./-/g")
-		echo -e "$(timestamp) [INFO] 구글 계정 ${ACCOUNT}"
+		echo -e "$(timestamp) 구글 계정 ${ACCOUNT}"
 		gcloud config set account ${ACCOUNT} &>/dev/null
+		echo
 	else
 		echo -e "$(timestamp) [ERROR] 구글 계정 확인 필요 ${ACCOUNT}"
+		echo
 		exit
 	fi
 }
 
 create_projects() {
-	echo
-	if [ -z "${PROJECT_EXIST}" ]; then
-		PROJECT=${ID}-${PROJECT_INFIX}-${1:-}
+	if [[ -n "${OLD_PROJECT_NAME}" ]]; then
+		# 기존 프로젝트 이름
+		PROJECT=${OLD_PROJECT_NAME}
 	else
-		PROJECT=${PROJECT_EXIST}
-		echo -e "$(timestamp) [INFO] 기존 프로젝트 이름 ${PROJECT_EXIST}"
+		# 신규 프로젝트 이름 : xxx-rclone01
+		# ${1:-} : 프로젝트 번호 by for loop
+		PROJECT="${ID}-${PROJECT_PREFIX}${1:-}"
 	fi
-	if [[ $(gcloud projects list 2>&1) != *"${PROJECT}"* ]]; then
-		echo -e "$(timestamp) [INFO] 프로젝트 생성 ${PROJECT}"
+	
+	gcloud config set project ${PROJECT} &>/dev/null
+	echo -e "$(timestamp) 프로젝트 목록"
+	local list=$(gcloud projects list)
+	echo -e "${list}"
+	echo
+	if [[ ${list} != *"${PROJECT}"* ]]; then
+		echo -e "$(timestamp) 프로젝트 생성 ${PROJECT}"
 		gcloud projects create ${PROJECT} &>/dev/null
 		local code=$?
-		if [ ${code} == 0 ]; then
-			echo -e "$(timestamp) [INFO] 프로젝트 목록"
-			gcloud projects list
-		else
+		if [[ ${code} != 0 ]]; then
 			echo -e "$(timestamp) [ERROR] 프로젝트 생성 불가 ${PROJECT}"
 			case ${code} in
 				1)
-					echo -e "+ 프로젝트 ID 중복으로 변수 값 수정 필요"
-					read -p "  PROJECT_INFIX=" PROJECT_INFIX
-					create_projects
-					return
+					echo -e "+ 프로젝트 ID 중복 ${PROJECT}"
 					;;
 				2)
-					echo -e "+ 프로젝트 ID 규칙 오류\n  \
-					https://cloud.google.com/sdk/gcloud/reference/projects/create?hl=ko#PROJECT"
-					exit
+					echo -e "+ 프로젝트 ID 규칙 오류"
+					echo -e "  https://cloud.google.com/sdk/gcloud/reference/projects/create?hl=ko#PROJECT"
 					;;
 				*)
-					echo -e "+ 프로젝트 할당량 초과\n  \
-					https://cloud.google.com/resource-manager/docs/creating-managing-projects?hl=ko#managing_project_quotas"
-					exit
+					echo -e "+ 프로젝트 할당량 초과"
+					echo -e "  https://cloud.google.com/resource-manager/docs/creating-managing-projects?hl=ko#managing_project_quotas"
+					echo -e "오류 코드 번호 : ${code}"
 					;; # 오류 코드 확인 필요
 			esac
+			echo
+			exit
 		fi
 		sleep 0.25s
 	fi
-	echo -e "$(timestamp) [INFO] 프로젝트 ${PROJECT}"
+	echo -e "$(timestamp) 프로젝트 선택 ${PROJECT}"
 	gcloud config set project ${PROJECT} &>/dev/null
+	echo
 }
 
 enable_apis() {
-	echo
-	local e_apis=("drive.googleapis.com") # 필수 apis
-	local d_apis="" # 불필요 apis
+	# 필수 APIs
+	local e_apis=("drive.googleapis.com")
+	
+	# 불필요 APIs
+	local d_apis=""
+	
+	# 필수 APIs 제외 필터
 	local filter=""
+	
+	# 필수 APIs 단일 라인
 	local tmp=""
+	
 	for api in ${e_apis[@]}; do
 		tmp+="${api} "
 		filter+="NOT config.name=${api} AND "
 	done
 	filter=${filter:0:-5}
+	
 	for api in $(gcloud services list --filter="${filter}" --format="table(NAME)" | sed 1d); do
 		d_apis+="${api} "
 	done
+	
 	e_apis=${tmp:0:-1}
+	
 	if [[ "${d_apis}" != "" ]]; then
-		echo -e "$(timestamp) [INFO] 불필요한 API 사용 중지"
+		echo -e "$(timestamp) 불필요한 API 사용 중지"
 		while read -r line; do
 			echo -e "- ${line}"
 		done <<< $(gcloud services list --filter="${filter}" --format="table(TITLE)" | sed 1d)
 		gcloud services disable --force ${d_apis:0:-1} &>/dev/null
+		echo
 	fi
-	echo -e "$(timestamp) [INFO] 구글 드라이브 API 사용"
+	echo -e "$(timestamp) 구글 드라이브 API 사용"
 	gcloud services enable ${e_apis} &>/dev/null
+	echo
 }
 
 create_sas() {
 	# 2020.08.12
 	# 서비스 계정 키를 다시 다운로드할 방법이 없다.
-	# 서비스 계정 키의 중복을 회피 하는 간단한 방법은 서비스 계정을 모두 삭제한 후 다시 생성하면 된다.
+	# 서비스 계정 키 중복을 회피하는 간단한 방법은
+	# 서비스 계정을 모두 삭제한 후 다시 생성하면 된다.
+
+	# 서비스 계정 목록
 	local list=$(gcloud iam service-accounts list --format="table(EMAIL)" | sed 1d)
+
+	# 서비스 계정 개수
 	local total=$(echo "${list}" | wc -l)
-	if [ -n "${list}" ]; then
-		echo
+	total=$(printf "%03d" ${total})
+
+	# 서비스 계정 키 중복 방지
+	if [[ -n "${list}" ]]; then
 		local count=1
 		for email in ${list}; do
-			echo -en "$(timestamp) [INFO] 기존 서비스 계정 삭제 (키 다중 생성 방지) : $(printf "%03d" ${count})/$(printf "%03d" ${total})개\r"
+			echo -en "$(timestamp) 기존 서비스 계정 삭제 (키 중복 방지) $(printf "%03d" ${count})/${total}개\r"
 			gcloud iam service-accounts delete ${email} --quiet &>/dev/null
 			((count++))
 		done
 		echo
+		echo
 	fi
-	echo
-	local tes=""    # total email string
-	local ess=",\n" # email string separator
-	FILE_EMAIL="accounts-${PROJECT}.txt"
+
+	# 서비스 계정 이메일 전체 내용
+	local tes=""
+
+	# 서비스 계정 이메일 내용 구분자
+	local ess=",\n"						
+
+	# 서비스 계정 이메일 정보 파일 : account-rclone01-xxx.txt
+	FILE_EMAIL="account-${PROJECT}.txt"
 	touch "${DIR_WORK}/${FILE_EMAIL}"
-	echo -e "$(timestamp) [INFO] 생성"
-	for num_s in $(seq -f "%03g" 1 ${NUM_SAS_PER_PROJECT}); do
-		# num_s = service account number
-		if [ ${num_s} == ${NUM_SAS_PER_PROJECT} ]; then
+	
+	echo -e "$(timestamp) 서비스 계정"
+	for num_s in $(seq 1 ${NUM_SAS_PER_PROJECT}); do
+		if [[ ${num_s} == ${NUM_SAS_PER_PROJECT} ]]; then
 			ess=""
 		fi
-		local num_p=${1:-} # project number
-		local name="p-${num_p}-sa-${num_s}"
+		num_s=$(printf "%03d" ${num_s})
+		NUM_SAS_PER_PROJECT=$(printf "%03d" ${NUM_SAS_PER_PROJECT})
+
+		# 프로젝트 번호
+		local num_p=${1:-}
+		
+		# 서비스 계정 이름 : xxx-p01-sa001
+		local name="${ID}-p${num_p}-sa${num_s}"
+		
+		# 서비스 계정 이메일 접두사 : xxx-p01-sa001@xxx-rclone01
 		local prefix=${name}@${PROJECT}
+		
+		# 서비스 계정 이메일
 		local email=${prefix}.iam.gserviceaccount.com
-		echo -en "$(timestamp) [INFO]   + 서비스 계정 ${num_s}/${NUM_SAS_PER_PROJECT}개\r"
+		
+		# 서비스 계정 생성
+		echo -en "$(timestamp) + 생성   ${num_s}/${NUM_SAS_PER_PROJECT}개 ${name}\r"
 		gcloud iam service-accounts create ${name} &>/dev/null
-		if [ ${num_s} == ${NUM_SAS_PER_PROJECT} ]; then
+		if [[ ${num_s} == ${NUM_SAS_PER_PROJECT} ]]; then
 			echo
 		fi
-		#sleep 0.25s
-		echo -en "$(timestamp) [INFO]   + 서비스 키   ${num_s}/${NUM_SAS_PER_PROJECT}개\r"
+		
+		# 서비스 계정 키 생성
+		echo -en "$(timestamp) + 키     ${num_s}/${NUM_SAS_PER_PROJECT}개\r"
 		gcloud iam service-accounts keys create "${DIR_WORK}/${DIR_KEY}/${prefix}.json" --iam-account=${email} &>/dev/null
-		if [ ${num_s} == ${NUM_SAS_PER_PROJECT} ]; then
+		if [[ ${num_s} == ${NUM_SAS_PER_PROJECT} ]]; then
 			echo
 		fi
-		#sleep 0.25s
-		echo -en "$(timestamp) [INFO]   + 이메일 정보 ${num_s}/${NUM_SAS_PER_PROJECT}개\r"
+		
+		# 서비스 계정 이메일 저장
+		echo -en "$(timestamp) + 이메일 ${num_s}/${NUM_SAS_PER_PROJECT}개\r"
 		if [[ ${tes} != *"${email}"* ]]; then
 			tes+=${email}${ess}
 		fi
-		if [ ${num_s} == ${NUM_SAS_PER_PROJECT} ]; then
+		if [[ ${num_s} == ${NUM_SAS_PER_PROJECT} ]]; then
 			echo
 		fi
     done
@@ -216,27 +335,31 @@ create_sas() {
 }
 
 check_sas() {
-	echo
 	sleep 1s
-	# service accounts count
+	echo
+	echo -e "$(timestamp) 확인"
+	echo -e "$(timestamp) + 프로젝트      ${PROJECT}"
+
+	# 서비스 계정 개수 확인
 	local cnt_s=$(gcloud iam service-accounts list --format="table(EMAIL)" | sed 1d | wc -l)
-	# count service accounts keys
+	echo -e "$(timestamp) + 서비스 계정   ${cnt_s}개"
+	
+	# 서비스 계정 키 개수 확인
 	local cnt_k=0
-	if [ -d "${DIR_WORK}/${DIR_KEY}" ]; then
+	if [[ -d "${DIR_WORK}/${DIR_KEY}" ]]; then
 		cnt_k=$(ls -al "${DIR_WORK}/${DIR_KEY}" | grep ".*@${PROJECT}\..*" | grep "^-" | awk "{print $9}" | wc -l)
 	fi
-	# service accounts email count
+	echo -e "$(timestamp) + 서비스 키     ${cnt_k}개, 폴더 ${DIR_WORK}/${DIR_KEY}/"
+	
+	# 서비스 계정 이메일 개수 확인
 	local cnt_e=$(cat "${DIR_WORK}/${FILE_EMAIL}" | wc -l)
-	echo -e "$(timestamp) [INFO] 확인"
-	echo -e "$(timestamp) [INFO]   + 서비스 계정   ${cnt_s}개"
-	echo -e "$(timestamp) [INFO]   + 서비스 키     ${cnt_k}개, 폴더 ${DIR_WORK}/${DIR_KEY}/"
-	echo -e "$(timestamp) [INFO]   + 서비스 이메일 ${cnt_e}개, 파일 ${DIR_WORK}/${FILE_EMAIL}"
+	echo -e "$(timestamp) + 서비스 이메일 ${cnt_e}개, 파일 ${DIR_WORK}/${FILE_EMAIL}"
+	echo
 }
 
 sas_email() {
 	if [[ -f "${DIR_WORK}/${FILE_EMAIL}" && $((${PROJECT_END}-${PROJECT_START})) == 0 ]]; then
-		echo
-		read -p "$(timestamp) [NOTICE] 서비스 계정 이메일 확인 (y/n)? " answer
+		read -p "$(timestamp) 서비스 계정 이메일 확인 (y/n)? " answer
 		case ${answer:0:1} in
 			y|Y)
 				cat "${DIR_WORK}/${FILE_EMAIL}"
@@ -247,9 +370,17 @@ sas_email() {
 }
 
 main() {
-	install_sdk
-	auth_login
-	for PROJECT_NUM in $(seq -f "%02g" ${PROJECT_START} ${PROJECT_END}); do
+	echo
+	echo -e "$(timestamp) 구글 서비스 계정 생성 스크립트"
+	echo
+	init
+	install
+	auth
+	for PROJECT_NUM in $(seq ${PROJECT_START} ${PROJECT_END}); do
+		if [[ $((${PROJECT_END}-${PROJECT_START})) != 0 ]]; then
+			echo
+		fi
+		PROJECT_NUM=$(printf "%02d" ${PROJECT_NUM})
 		for function in create_projects enable_apis create_sas check_sas sas_email; do
 			eval ${function} "${PROJECT_NUM}"
 		done
